### ISSUE TITLE
Function to return vector string without not defined (X) values

### ISSUE THREAD

**Issue by Fubinator** [turingsecure/cvss.js#63]
Sometimes it is useful for the user to get a string without any metrics that are not defined (so value =  "X"). We should implement a function `getCleanVectorString()` that returns a string without those values.

So instead of
```
CVSS:3.0/AV:L/AC:L/PR:H/UI:N/S:U/C:N/I:H/A:N/E:P/RL:W/RC:X/CR:X/IR:X/AR:M/MAV:A/MAC:X/MPR:X/MUI:N/MS:X/MC:X/MI:X/MA:X
```

The function should return
```
CVSS:3.0/AV:L/AC:L/PR:H/UI:N/S:U/C:N/I:H/A:N/E:P/RL:W/AR:M/MAV:A/MUI:N
```

**Comment by jackson541** [comment]
Hello @Fubinator , can i get this issue?
