### ISSUE TITLE
Get qualitative rating for temporal and environmental score

### ISSUE THREAD

**Issue by Fubinator** [turingsecure/cvss.js#66]
Currently it is only possible to get a qualitative rating for the base score using the getRating() function. However, it is also important to be able to retrieve this rating for the Temporal and Environmental Score. I think we should create a public function (getTemporalRating and getEnvironmentalRating) for both scores

**Comment by sosavle** [comment]
I can do that 👍

**Comment by Fubinator** [comment]
Sure, go ahead @sosavle !

**Comment by sosavle** [comment]
I think I did the thing! Let me know if it's what you were hoping for. I'm also open to helping out on other issues, since I already familiarized myself with the code :)

**Comment by Fubinator** [comment]
@sosavle We don't have that much to do in terms of functionality anymore. You are welcome to check this repo from time to time to see if there are new things to do. #62 is the only thing that needs to be implemented relatively urgently, but I don't know exactly what to do.
