### ISSUE TITLE
Invalid CVSS3.1 scores in some cases

### ISSUE THREAD

**Issue by Rogdham** [turingsecure/cvss.js#72]
Hello :wave: I noticed that some scores differ from the First calculator.

Example:
 - Vector: `CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:H/I:H/A:H`
 - [First calculator scores](https://www.first.org/cvss/calculator/3.1#CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:H/I:H/A:H): 9.6 (base), 9.6 (temporal), 9.7 (environmental)
 - [NIST calculator scores](https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator?vector=AV:N/AC:L/PR:N/UI:R/S:C/C:H/I:H/A:H&version=3.1): 9.6 (base) (NIST calculator does not show temporal/environmental score when they are all `X`s)
 - This lib score: 9.7 (base), 9.7 (temporal), 9.7 (environmental)

```js
const CVSS = require("@turingpointde/cvss.js");

const vector = CVSS("CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:H/I:H/A:H");
console.log("base", vector.getScore());
console.log("temporal", vector.getTemporalScore());
console.log("environmental", vector.getEnvironmentalScore());
```

**Comment by Fubinator** [comment]
Good catch! I'm going to look into this.

**Comment by Fubinator** [comment]
I've fixed it in #73. There were a few wrong calculations. For future reference: The impact sub score is different for base and environmental ratings.

**Comment by Rogdham** [comment]
Woah, that was fast, thank you @Fubinator I will try the patch when I have a minute and report back :hugs:

**Comment by Rogdham** [comment]
Update: I compared the values for few dozen million different CVSS3.1 vectors, and everything is as expected! :tada:
