### ISSUE TITLE
Version 1.4.7 is not published on npm registry

### ISSUE THREAD

**Issue by antoinm** [turingsecure/cvss.js#91]
It seems like the version 1.4.7 has not been published on the npm registry. 

Was it done on purpose or it is a mistake ?

**Comment by Fubinator** [comment]
This was a mistake on my side. I'm fixing this right now. Thanks for reporting!

**Comment by Fubinator** [comment]
1.4.7 was just published on npm:

https://www.npmjs.com/package/@turingpointde/cvss.js?activeTab=versions
